#! /bin/sh

# Return status code of a comparison
float_test()
{
  echo | awk 'END { exit (!  ('"$1"')); }'
}

if which gcalcli &> /dev/null; then
  time=$(gcalcli remind 30 'echo %s' | head -1 | cut -d' ' -f5)

  float_test "$time <= 30  && $time > 20"  && echo -e "Event "
  float_test "$time <= 20  && $time > 10"  && echo -e "\005{= kW}Event "
  float_test "$time <= 10  && $time > 2 "  && echo -e "\005{= kY}Event "
  float_test "$time <= 2"                  && echo -e "\005{= kR}Event "
fi
