#!/usr/bin/env python
# encoding: utf-8

# File        : host
# Author      : Ben Wu
# Contact     : benwu@fnal.gov
# Date        : 2015 Jan 18
#
# Description :

import commands
import os
cap=commands.getoutput('xset q | grep LED')[65]
host=os.environ.get('SHORT_HOST')
if cap == '0':
    print host
if cap == '1':
    print "\005{= kR}%s\005{-}" % host







