#!/usr/bin/env python
# encoding: utf-8

# File        : test.py
# Author      : Ben Wu
# Contact     : benwu@fnal.gov
# Date        : 2012 Jul 02
#
# Description : Since the checkmail could cause a small pause of the screen,
# I now separate it out from the screen update. Screen will run this script to
# read from the status file for email info. And it would send the checkmail
# job as independent process (thanks to setsid) in parallel with running
# screen. Now this should be running smoothly with the scarification that the
# email will be know after 10 mins instead of 5 now.

import os
import subprocess
import re
import datetime


if __name__ == "__main__":
    ## Predefine delta, for the case the status file is empty, it would send
    ## out a new checkmail
    delta = datetime.timedelta(minutes = 5)

    ## Touch status if it does not exist
    if not os.access("status", os.R_OK):
        os.system("touch status")

    try:
        f = open("status", 'r')
        line = f.readline()
        echo = re.match('.*(\[.*\])$', line.strip())
        if echo == None:
            echo = "None"
        else:
            echo = echo.group(1)

        s = re.sub('\..*', '', line).strip()
        t = datetime.datetime.strptime(s, '%Y-%m-%d %H:%M:%S')
        delta =  datetime.datetime.now() - t
        f.close()
    except:
        proc = subprocess.Popen( '~/.screen/checkmail > status', shell=True, preexec_fn = os.setsid ) 
    finally:
        if delta > datetime.timedelta(minutes = 20):
            p = subprocess.Popen( '~/.screen/checkmail', shell = True,
                                   stdout=subprocess.PIPE)
            out = p.stdout.read()
            echo = re.match('.*(\[.*\])$', out)
            if echo == None:
                echo = "None"
            else:
                echo = echo.group(1)
                print echo
        else:
            if echo != "None":
                print echo
            proc = subprocess.Popen( '~/.screen/checkmail > status', shell=True, preexec_fn = os.setsid ) 
