#!/bin/tcsh

cmsenv
set cdpath=($CMSSW_BASE/src ~/)
setenv LANG en_US.UTF8
set __git_cmd_names="cms-addpkg cms-merge-topic cms-checkdeps $__git_cmd_names"

## Setup clang_complete
if (! -e $CMSSW_BASE/src/.clang_complete) then
  touch $CMSSW_BASE/src/.clang_complete
  echo -I$CMSSW_BASE/src >> $CMSSW_BASE/src/.clang_complete
  echo -I$CMSSW_RELEASE_BASE/src >> $CMSSW_BASE/src/.clang_complete
  if (`which root-config >& /dev/null ; echo $?`  == 0 ) then
    foreach cmd (`root-config --cflags`)
      echo $cmd >> $CMSSW_BASE/src/.clang_complete
    end
  endif
  ## Nbay04 can handle large loading
  if (  $SHORT_HOST =~ nbay04 ) then 
    foreach fwlite (`echo $CMSSW_FWLITE_INCLUDE_PATH | tr ':' '\n'`)
      echo -I$fwlite >> $CMSSW_BASE/src/.clang_complete
    end
  endif
endif

## Setup command completion
#complete gzcat	c/--/"(force help license quiet version)"/ \
  #c/-/"(f h L q V -)"/ n/*/f:*.{gz,Z,z,zip}/
