#!/bin/csh

set texfile=0
set targs=()

if ($#argv == 0) then
  set file=""
endif

foreach arg ($*)
  if ( "$arg" =~ [-]* ) then
     set targs = ($targs $arg)
     continue
  endif

  set file=`basename $arg | awk -F. '{print $NF}'`
  foreach tex (tex bib bst sty)
    if ($file == $tex) then
      set texfile=1
    endif
  end

  if (`echo $arg | grep -c ":"`) then
    set temp = "scp://`echo ${arg} | sed -e 's@:/@//@' | sed -e 's@:@/@'`"
    set targs = ($targs $temp)
  else
    set targs = ($targs $arg)
  endif

end


${CVSEIDTOR} --servername $USER $targs

#if ($texfile == 1) then
  #${CVSEIDTOR} --servername $USER $targs
#else
  #${CVSEIDTOR} -X $targs
#endif
